#!/bin/bash

################################################################################
#                                                                              #
#                      CD2MP3 v1.0 - CD to MP3 Conversion                      #
#                  Used to convert an entire CD to MP3 files.                  #
#                                                                              #
################################################################################

# Standard cdparanoia command to rip all tracks from 1 onwards
# B should create individual tracks, z accepts no errors, 1 skips the leader

################################################################################
#                                                                              #
#                        Load standard shell functions                         #
#                                                                              #
################################################################################

debecho () {
if [ ! -z "$DEBUG" ]; then
	echo ">> ${1}" >&2
fi
}

checkfor () {
for checkit in ${*}; do
	if ! which ${checkit} &> /dev/null; then
		echo "Pre-requisites not met -- ${checkit} is not installed."
		exit 99
	fi
done
}

################################################################################
#                                                                              #
#                          Main body of script here.                           #
#                                                                              #
################################################################################

checkfor cdparanoia lame eject
debecho "All prerequisites found..."

if [ -n "${1}" ]; then
   mkdir -p "${1}"
   cd "${1}"
fi

cdparanoia -B -z 1- &&
   eject /dev/cdrom

# Start a sub-shell to process the odds: 1, 3, 5, 7, 9

(
   for i in track?[1,3,5,7,9].cdda.wav; do
      echo "Encoding ${i} with LAME VBR 4..." &&
      lame -V 4 --quiet ${i} &&
      rm ${i}
   done
) &

# Process the evens in the current shell: 2, 4, 6, 8, 0

for j in track?[2,4,6,8,0].cdda.wav; do
   echo "Encoding ${j} with LAME VBR 4..." &&
   lame -V 4 --quiet ${j} &&
   rm ${j}
done

# Wait until all tasks have completed
wait
